### ISSUE TITLE
Unable to Checkout Using SSH Protocol

### ISSUE THREAD

**Issue by jancrot** [ceilfors/daun#2]
[hendraj@ukfhpapgsg02 src]$ daun init ssh://git@bitbucketglobal.mycompany.local/pow/product.git .

[hendraj@ukfhpapgsg02 src]$ daun checkout
Fetching git repository..
/usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:78:in `fetch': Unsupported URL protocol (Rugged::NetworkError)
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:78:in `fetch_refs'
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:34:in `checkout'
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/cli.rb:17:in `checkout'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/share/gems/gems/daun-0.1.2/exe/daun:3:in `<top (required)>'
        from /usr/local/bin/daun:23:in `load'
        from /usr/local/bin/daun:23:in `<main>'

**Comment by ceilfors** [comment]
Not a daun bug. You will need to install the relevant Linux package before installing rugged. In CentOS for example, you should install `libssh2-devel` package.

Once you have set rugged up correctly, you should see https in the following output:

```
$ ruby -e "require 'rugged'; puts Rugged.features"
threads
https
ssh
```
