### ISSUE TITLE
Unable to Checkout After Setting daun.tag.limit

### ISSUE THREAD

**Issue by jancrot** [ceilfors/daun#3]
[hendraj@ukfhpapgsg02 demo]$ daun init http://hendraj:password@bitbucketglobal.mycompany.local/scm/pow/product.git src
[hendraj@ukfhpapgsg02 demo]$ cd src/
[hendraj@ukfhpapgsg02 src]$ git config daun.tag.limit 10
[hendraj@ukfhpapgsg02 src]$ cat .git/config
[core]
        bare = false
        filemode = true
        logallrefupdates = true
[core]
        repositoryformatversion = 0
[remote "origin"]
        url = http://hendraj:password@bitbucketglobal.mycompany.local/scm/pow/product.git
[remote "origin"]
        fetch = +refs/heads/*:refs/remotes/origin/*
[daun "tag"]
        blacklist = ""
[daun "tag"]
        limit = 10
[daun "branch"]
        blacklist = ""

[hendraj@ukfhpapgsg02 src]$ daun checkout
Fetching git repository..
/usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:127:in `take': attempt to take negative size (ArgumentError)
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:127:in `keep_new_tags'
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:83:in `fetch_refs'
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:34:in `checkout'
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/cli.rb:17:in `checkout'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/share/gems/gems/daun-0.1.2/exe/daun:3:in `<top (required)>'
        from /usr/local/bin/daun:23:in `load'
        from /usr/local/bin/daun:23:in `<main>'

**Comment by ceilfors** [comment]
This bug will happen when the set tag limit is more than the number of real tags. Will be fixed in 0.1.3.

**Comment by ceilfors** [comment]
@jancrot Released 0.1.3 to rubygems.org.
