### ISSUE TITLE
authentication required but no callback set 

### ISSUE THREAD

**Issue by jancrot** [ceilfors/daun#4]
Private key and public key set up properly.. confirmed!

Using git directly:
[opengrok@ukfhpapgsg02 test]$ git clone ssh://git@bitbucketglobal.company.local/pow/collections-pom.git collections-pom
Cloning into 'collections-pom'...
remote: Counting objects: 129, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 129 (delta 71), reused 129 (delta 71)
Receiving objects: 100% (129/129), 17.62 KiB | 0 bytes/s, done.
Resolving deltas: 100% (71/71), done.

Using daun:
[opengrok@ukfhpapgsg02 test]$ daun init ssh://git@bitbucketglobal.company.local/pow/collections-pom.git collections-pom
[opengrok@ukfhpapgsg02 test]$ cd collections-pom/
[opengrok@ukfhpapgsg02 collections-pom]$ daun checkout
Fetching git repository..
/usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:78:in `fetch': authentication required but no callback set (Rugged::SshError)
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:78:in `fetch_refs'
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/rugged_daun.rb:34:in `checkout'
        from /usr/local/share/gems/gems/daun-0.1.2/lib/daun/cli.rb:17:in `checkout'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/share/gems/gems/daun-0.1.2/exe/daun:3:in `<top (required)>'
        from /usr/local/bin/daun:23:in `load'
        from /usr/local/bin/daun:23:in `<main>'

**Comment by mlosev** [comment]
have the same issue with access to git private repos via ssh

**Comment by ceilfors** [comment]
You can use the http protocol with the following format for temporary workaround: https://**user:pass**@github.com/project/repo.git.

**Comment by ceilfors** [comment]
Fix is released under 0.2.0. Thanks to @mlosev for #5 and #6.
